name: Build and Deploy

on:
  push:
    branches: main

jobs:
  build-and-deploy:
    name: Build and deploy Recipes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.1

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          sudo chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H -p ${{ secrets.SSH_PORT }} "${{ secrets.HOST }}" > ~/.ssh/known_hosts

      - name: SCP upload
        run: scp -r -P ${{ secrets.SSH_PORT }} -i ~/.ssh/deploy_key public/* ${{ secrets.DEPLOY_USER }}@${{ secrets.HOST }}:${{ secrets.DESTINATION_PATH }}
